apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-aws 
spec:
  interval: 30s
  chart:
    spec:
      chart: ./charts/capi-aws
      sourceRef:
        kind: GitRepository
        name: capi-aws
      interval: 1m
      valuesFiles:
        - charts/capi-aws/values-demo.yaml 
